source 'https://github.com/zhouyi123/XRCategoryKit'
source 'https://github.com/zhouyi123/XRSpecs'

platform :ios, '8.0'

target 'XRCategoryKit_Example' do
  pod 'XRCategoryKit', :path => '../'

  target 'XRCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
