
source '[https://github.com/zhouyi123/XRSpecs.git](https://github.com/zhouyi123/XRSpecs.git)’
source '[https://github.com/CocoaPods/Specs.git](https://github.com/CocoaPods/Specs.git)’
platform :ios, '8.0'

target 'XRCategoryKit_Example' do
  pod 'XRCategoryKit', :path => '../'

  target 'XRCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
